name: 'crowdin-actions'

description: 'Upload crowdin translations'

inputs:
  upload_sources:
    description: 'Upload sources to Crowdin'
    default: 'true'
    required: false
  upload_translations:
    description: 'Upload translations to Crowdin'
    default: 'false'
    required: false
  branch_name:
    description: 'To upload or download files to the specified version branch'
    required: false
  dryrun_action:
    description: 'Option to preview the list of managed files'
    required: false
    default: 'false'
  download_translations:
    description: 'Make pull request of Crowdin translations'
    default: 'false'


runs:
  using: docker
  image: 'Dockerfile'
